### PR TITLE
Fix fnullable

### PR DESCRIPTION
**Pull request by k-bx**
Fixes https://github.com/bartavelle/json-helpers/issues/8

I couldn't figure out how to run tests, so I didn't make one.

```
➜  json-helpers git:(master) elm-test               
It looks like you're running elm-test from within your tests directory.

Please run elm-test from your project's root directory, where its elm-package.json lives!
```

Help appreciated.

### CODE REVIEW

**Comment by k-bx** [comment]
One thing to note is, I'm not sure if we'd like the code to still work when the key is absent or not, but I couldn't make it work. This doesn't work for example:

```elm
> Json.Decode.decodeString (Json.Decode.nullable (Json.Decode.field "foo" (Json.Decode.nullable Json.Decode.int))) "{}"            
Err (OneOf [Failure ("Expecting null") <internals>,Failure ("Expecting an OBJECT with a field named `foo`") <internals>])
    : Result Json.Decode.Error (Maybe (Maybe Int))
```

**Comment by bartavelle** [comment]
(Looking at it, but do not worry about the tests, this was an 0.18 thing, and it was a hack anyway, there is no proper testing in Elm :( )

**Comment by bartavelle** [comment]
I think you can make it work by using `oneOf`, something like:

    oneOf [ (the thing I had previously), (the thing you just wrote) ]

Does that work for you?

**Comment by bartavelle** [comment]
However I do not think it is a good idea, as you can't choose the behavior anymore. You can however get to what you wanted by using a standard field and prefixing the decoder by nullable, can't you?

**Comment by k-bx** [comment]
@bartavelle I get what I want by the change in this PR, it would make the current code generated by elm-bridge work, and `fnullable` would have a behavior correctly working on fields with a `null` value. Do you see any reasons not to merge at the moment?

**Comment by bartavelle** [comment]
`fnullable` decodes missing keys as `Nothing`. AFAIU, your change decodes keys with `null` fields as `Nothing`. You could get the same result by using something like `field "foo" (nullable decoder)`, or something like that, I do not have the exact Elm wording in mind :/

**Comment by k-bx** [comment]
> fnullable decodes missing keys as Nothing

Sorry, I think I don't fully understand what you mean by this claim. Do you mean:

1. that `fnullable` in this package is intended to only handle the "missing field" scneario, and we should fix it plus the `elm-bridge` to handle the null-value case
2. that `fnullable` works correctly as of right now (which I don't find to be the case) and we should only change elm-bridge?

Thanks

**Comment by bartavelle** [comment]
I think that both positions have merit. There is definitely a bug in Elm-bridge though! How did you generate the code? How was the missing-field thingie set in the option record?

**Comment by bartavelle** [comment]
My position would be that the case where the content of a field can be null is no different than in any other places where you can have null, and should not be handled with a specific combinator.

**Comment by k-bx** [comment]
I generate my code with something like this:

```haskell
data Foo 
  = Foo
  { fooFieldOne :: Maybe Int
  , fooFieldTwo :: String }
  deriving (Generic)

jsonOpts :: Int -> J.Options
jsonOpts n = J.defaultOptions {J.fieldLabelModifier = J.camelTo2 '_' . drop n}

deriveBoth (jsonOpts 3) ''Foo
```

I could definitely just set options to not render null fields, but I think this should also be fixed in elm-bridge to not confuse other users, plus I personally prefer to render fields with a null value (to have a fixed schema).

Not sure when I'll have time to make a PR to elm-bridge unfortunatley.

**Comment by k-bx** [comment]
Forgot to add, it's lts-12.10, so it's aeson-1.3.1.1

**Comment by bartavelle** [comment]
I fixed `json-helpers` documentation, and I will look into the `elm-bridge` bug.

**Comment by bartavelle** [comment]
I incorporated your suggestion into a patch that handles both use cases before working on `elm-bridge`. Does that currently work for you?

**Comment by k-bx** [comment]
I've seen the change, it looks good, no need to fix elm-bridge with it, I believe.

New version release would be appreciated. Thank you!

**Comment by bartavelle** [comment]
done! thanks for the feedback!

**Pull request closed without merging**
